name: pull_request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ github.head_ref }}
        run: docker build . --file Dockerfile --tag $REPO_NAME:$REPO_BRANCH

      - name: Get the docker image testing material
        run: wget -O test_docker_call.py https://raw.githubusercontent.com/eurobench/docker_test/master/test_docker_call.py

      - name: test the docker image
        env:
          TEST_PLAN: testdata/test_plan.xml
          DOCKER_IMAGE: ${{ github.event.repository.name }}:${{ github.head_ref }}
        run: python3 test_docker_call.py
